# Datasource MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mcpe1234
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/quarkusdb

# Hibernate — cria/atualiza tabelas automaticamente
quarkus.hibernate-orm.database.generation=update

# Log SQL (opcional, útil no dev)
quarkus.hibernate-orm.log.sql=true