spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    notification: pedido.notification
    carried-data: pedido.carried-data
    event-sourcing: conta.event-sourcing

logging:
  level:
    com.event: DEBUG

