spring.application.name=Brainweb Interview

## Server properties
server.compression.enabled=true
server.http2.enabled=true
server.compression.mime-types=application/json
spring.jackson.serialization.write_dates_as_timestamps=true
spring.jackson.mapper.propagate_transient_marker=true
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.default-property-inclusion=non_null

## Banco de dados - Configuração PADRÃO do Spring Boot
spring.datasource.url=jdbc:postgresql://localhost:5435/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=interview_service

# JPA - desativa validação de schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=interview_service
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

## Flyway (opcional - comente se não estiver usando)
spring.flyway.enabled=false
spring.flyway.schemas=interview_service