spring.application.name=kafka-patterns
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest

# Isso ajuda a ver os logs dos nossos consumidores de forma clara
logging.level.com.example.patterns=DEBUG